name: Android Build

#on: pull_request
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#      - uses: actions/checkourv1 #Can be used when triggered on pull_request
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

#      - name: Run Tests
#        run: ./gradlew test

#      - name: Generate Version Catalog
#        run: ./gradlew generateCatalogsAsToml

      - name: Build Project
        run: ./gradlew build
