name: Android Debug Build

#on: pull_request
on: [push]
#  workflow_dispatch:
#  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle')}}
          restore-keys: |
            ${{runner.os}}-gradle-

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Publish APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: New Build
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk

  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: DownloadAPK from build
        uses: actions/download-artifact@v1
        with:
          name: androidApp-debug
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: androidApp-debug${{ github.event.inputs.version }}.apk

