name: iOS Debug Build

on:
  push:
    branches:
      - master
  workflow_dispatch:
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Build
        run: ./gradlew :shared:iosX64Test

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: iosApp/iosApp.xcworkspace
          scheme: iosApp
          destination: name=iPhone 14
          sdk: iphoneos
          configuration: Debug
          action: build